# 🙌 Configuration des Systems

general:
  gpt_directory: "/mnt/data/gpt/"
  dynamic_prompts_directory: "/mnt/data/gpt/dynamic_prompts/"
  user_requests_directory: "/mnt/data/gpt/user_requests/"
  local_files_directory: "/mnt/data/gpt/local_files/"
  log_file: "/mnt/data/gpt/local_files/logs/system.log"

fail_prompts:
  enabled: true
  root_path: "/mnt/data/gpt/"