name: Convert Encoding ISO-8859-1 to UTF-8

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Manuelles Auslösen möglich

jobs:
  convert_encoding:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Finde und konvertiere ISO-8859-1-Dateien
        run: |
          # Suche nach Dateien mit ISO-8859-1 (Anpassung nötig, falls Dateiendungen bekannt sind)
          find . -type f -exec file --mime {} + | grep 'iso-8859-1' | cut -d: -f1 | while read file; do
            echo "Konvertiere: $file"
            iconv -f ISO-8859-1 -t UTF-8 "$file" -o "$file.utf8"
            mv "$file.utf8" "$file"
          done

      - name: Prüfe auf Änderungen
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          if git diff --cached --quiet; then
            echo "Keine Änderungen, Commit wird übersprungen."
          else
            git commit -m "🔄 Automatische Konvertierung von ISO-8859-1 zu UTF-8"
            git push
          fi
