name: Fix Encoding Issues (ISO-8859-1 → UTF-8)

on:
  push:
    paths:
      - "docs/**"  # Überprüft alle Dateien im "docs"-Ordner
  workflow_dispatch: # Manuelles Starten der Action möglich

jobs:
  fix_encoding:
    runs-on: ubuntu-latest
    steps:
      - name: Repository klonen
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Verhindert Probleme mit "detached HEAD"

      - name: Erstelle Log-Datei
        run: echo "Encoding Fix Log - $(date)" > encoding-fix.log

      - name: Überprüfe und fixe Encoding-Fehler (ISO-8859-1 → UTF-8)
        run: |
          for file in $(find docs -type f); do
            echo "🔍 Prüfe Datei: $file" | tee -a encoding-fix.log
            
            # Prüfe, ob Datei NICHT in UTF-8 ist
            if file -i "$file" | grep -q "charset=iso-8859-1"; then
              echo "⚠ Datei ist in ISO-8859-1: $file → Konvertiere nach UTF-8" | tee -a encoding-fix.log
              mv "$file" "$file.bak"
              iconv -f ISO-8859-1 -t UTF-8 "$file.bak" -o "$file" || { echo "❌ Konvertierung fehlgeschlagen: $file" | tee -a encoding-fix.log; mv "$file.bak" "$file"; continue; }
              rm "$file.bak"
              echo "✅ Datei erfolgreich konvertiert: $file" | tee -a encoding-fix.log
              git add "$file"
            else
              echo "✅ Datei ist bereits UTF-8: $file" | tee -a encoding-fix.log
            fi
          done

      - name: Änderungen committen (falls nötig)
        run: |
          if git diff --staged --quiet; then
            echo "🚀 Keine Änderungen gefunden, kein Commit nötig." | tee -a encoding-fix.log
            exit 0
          else
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git commit -m "🔥 Automatische Konvertierung von ISO-8859-1 nach UTF-8"
          fi

      - name: Änderungen pushen
        run: |
          git branch --show-current
          git pull --rebase origin main  # Verhindert Merge-Konflikte
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log-Datei als Artefakt speichern
        uses: actions/upload-artifact@v4
        with:
          name: encoding-fix-log
          path: encoding-fix.log

