name: Fix Encoding Issues and Base64 Decoding

on:
  push:
    paths:
      - "docs/**"  # Überprüft nur Dateien im "docs"-Ordner
  workflow_dispatch: # Manuelles Starten der Action möglich

jobs:
  fix_encoding:
    runs-on: ubuntu-latest
    steps:
      - name: Repository klonen
        uses: actions/checkout@v4

      - name: Erstelle Log-Datei
        run: echo "Encoding Fix Log - $(date)" > encoding-fix.log

      - name: Überprüfe und fixe Encoding-Fehler + Base64-Fehler
        run: |
          for file in $(find docs -type f); do
            echo "🔍 Prüfe Datei: $file" | tee -a encoding-fix.log
            
            # Backup erstellen
            cp "$file" "$file.bak"

            # Prüfe, ob Datei Base64-kodiert ist (nur wenn sie nicht zu klein ist)
            if grep -qE "^[A-Za-z0-9+/=]+$" "$file" && [ $(wc -c < "$file") -gt 100 ]; then
              echo "⚠ Datei könnte Base64-kodiert sein, dekodiere sie..." | tee -a encoding-fix.log
              if base64 --decode "$file" > "$file.decoded" 2>/dev/null; then
                mv "$file.decoded" "$file"
                echo "✅ Base64 erfolgreich dekodiert: $file" | tee -a encoding-fix.log
              else
                echo "❌ Base64-Dekodierung fehlgeschlagen: $file" | tee -a encoding-fix.log
                continue
              fi
            fi

            # Prüfe, ob Datei bereits UTF-8 ist
            if file -i "$file" | grep -q "charset=utf-8"; then
              echo "✅ Datei ist bereits UTF-8: $file" | tee -a encoding-fix.log
              continue
            fi

            # Konvertiere nach UTF-8 (Fehler ignorieren, falls nicht möglich)
            if ! iconv -f utf-8 -t utf-8 "$file" -o "$file" 2>/dev/null; then
              echo "❌ Fehler bei iconv für Datei: $file, speichere Sicherungskopie." | tee -a encoding-fix.log
              mv "$file" "$file.failed"
              continue
            fi

            # Prüfe, ob Änderungen vorgenommen wurden
            if ! cmp -s "$file" "$file.bak"; then
              echo "✅ Datei $file wurde korrigiert!" | tee -a encoding-fix.log
              git add "$file"
            else
              echo "✅ Datei $file war bereits korrekt!" | tee -a encoding-fix.log
            fi

            # Backup entfernen
            rm "$file.bak"
          done

      - name: Änderungen committen (falls nötig)
        run: |
          if git diff --staged --quiet; then
            echo "🚀 Keine Änderungen gefunden, kein Commit nötig." | tee -a encoding-fix.log
          else
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git commit -m "🔥 Automatische Korrektur von Encoding- und Base64-Fehlern"
            git push
          fi

      - name: Log-Datei als Artefakt speichern
        uses: actions/upload-artifact@v4
        with:
          name: encoding-fix-log
          path: encoding-fix.log

